packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  svelte-preprocess: true
  '@sveltejs/kit': true
minimumReleaseAgeExclude:
  - sveltekit-flash-message
  - sveltekit-rate-limiter
  - eslint-plugin-dci-lint
